### ISSUE TITLE
Add a MediaType for `application/x-protostream`

### ISSUE THREAD

**Issue by rigazilla** [infinispan/js-client#72]
[Protostream](https://github.com/infinispan/protostream) is a Protobuf based serialization library, is used by Infinispan to serialize cache entries preserving their type.

Protostream message is defined here [link](https://github.com/infinispan/protostream/blob/main/core/src/main/resources/org/infinispan/protostream/message-wrapping.proto) 

Client should support protobuf encode/decode for mediatype `application/x-protostream`.
MediaType initialization seems to be here [link](https://github.com/infinispan/js-client/blob/bac3b432c6b7dd5e5fd83c165edd998d959d1545/lib/protocols.js#L846-L847)

Protostream encoder/decoder should be added here [link](https://github.com/infinispan/js-client/blob/bac3b432c6b7dd5e5fd83c165edd998d959d1545/lib/protocols.js#L748)

I've found an example of js protobuf usage here [link](https://thecodebarbarian.com/working-with-protobufs-in-node-js.html) based on protobufjs, but maybe better examples are available...

**Comment by rigazilla** [comment]
**Meeting notes (@rigazilla  , @NeerajGartia21 )**

`application/x-protostream` media type is based upon the [WrappedMessage](https://github.com/infinispan/protostream/blob/main/core/src/main/resources/org/infinispan/protostream/message-wrapping.proto) protobuf message.
In a WrappedMessage the user can send:
- basic data types, see the list in the `oneof ScalarOrMessage` definition
- generic protobuf message marshalled as bytes array. In this case client and server must agree on an identifier for each data type that allows the proper (un)marshalling on both sides. This id is stored into the [wrappedTypeId](https://github.com/infinispan/protostream/blob/3e5380935b3c79a02e1386aa4d651f19ab780c67/core/src/main/resources/org/infinispan/protostream/message-wrapping.proto#L106) field.

**The plan**

- [ ] task 1: the js client should be enabled to encode/decode WrappedMessage using the [protobufjs](https://github.com/protobufjs/protobuf.js/) library. The `message-wrapping.proto` should be considered internal implementation and not exposed to the user.

- [ ] task 2: WrappedMessage enc/decoding should be activated when the `application/x-protostream`is set by the user. 
3. A Get/Put operation of a user object should result in a sequence of operation
    a. the user object is encoded
    b. stored in the [wrappedMessage](https://github.com/infinispan/protostream/blob/3e5380935b3c79a02e1386aa4d651f19ab780c67/core/src/main/resources/org/infinispan/protostream/message-wrapping.proto#L74) field
    c. and identified with the correct id into the wrappedTypeId field

Before to work on 3 we must design how the js client could maintain the relation between (user type, en/decoder, type id)

**Proposal **
The user at setup time should register to the client the tuple (type, en/decoder, id) for each protobuf message type he wants to send/receive.
Get/Put should work like this:
_Put_
1. user request put(key,value)
2. client detects key type and map it to the relative encoder and id
3. client encodes the key with the encoder and put the resulting bytes array into the message together with the type id
4. same procedure for the value
5. client sends the put request

_Get_
1. user request get(key)
2. client detects key type and map it to the relative encoder and id
3. client encodes the key with the encoder and put the resulting bytes array into the message together with the type id
4. client sends the get request
5. client upon response decodes the WrappedMessage
6. client using the received wrappedTypeId get the correct decoder and use it to decode the user object
7. object is returned to the user application

@NeerajGartia21 let me know if I forgot something or something is unclear.
Also let me know how does the proposal above sounds to you!

**Comment by NeerajGartia21** [comment]
I think all the things are covered and the proposal sounds good to me.

**Comment by rigazilla** [comment]
**Use case pseudo code**
_User wants to put(key,value)_

_Setup time_
1. user registers all the protobuf types he wants to cache, i.e.:
    a. registerProtrostreamType(User, descriptorId=1)
    b. registerProtostreamType(Address, descriptorId=1)
2. use sets `application/x-protostream` mediatype for key and value

 _Working time_
1. user calls `put(key,value)`
2. clients calls protostream for en/decoder
3. protostream generates a WrappedMessage and write it to the out buffer, so it does something like:
    a. wm = new WrappedMessage()
    b. (encoder, descriptorId) = lookupProtostreamType(key)
    c. bytes = encoder(key)
    d. wm.WrappedMessageBytes = bytes
    e. wm.WrappedDescriptorId = descriptorId
    f. encodedWm = wm.encode()
   g. bytebuf.write(encodedWm)
4. same for the value argument

**Comment by rigazilla** [comment]
I've looked into a little bit more into the protobuf.js library, I think a simpler design is possible if we:
1. restrict the implementation only to protobuf.js `Message instances` [see](https://github.com/protobufjs/protobuf.js#valid-message);
2. leave to the user the job of manage his own protobuf objects

Restricting put/get operation to `Message instances` only has two advantages:
1. we can directly ask the object to encode/decode itself, so no need to handle encoder and decoder direclty;
2. excluding `Plain JavaScript Objects` removes the problem to identify to which protobuf message a plain js object belongs to, since it could be considered valid for more than one protobuf message definition.

_Setup Time_
1. user registers all the protobuf types he wants to cache, i.e.:
    a. registerProtrostreamType(string "User", int descriptorId=1)
    b. registerProtostreamType(string "Address", int descriptorId=2)
3. use sets `application/x-protostream` mediatype for key and value

Scope of the `registerProtostreamType` function is to build a map that maintains the relation between the Message instance type name and the protostream wrapped descriptor id. No more need to include the enc/decoder into this map.

 _Working time_
_Put use case_
1. user calls `put(key,value)` // Both key and value are protobuf.js Message instances
2. clients calls protostream for en/decoder
4. protostream generates a WrappedMessage and write it to the out buffer, so it does something like:
    a. wm = new WrappedMessage()
    b. encoder, descriptorId = lookupProtostreamTypeByName(key.$type.name)
    c. bytes = key.$type.encode(key).finish(); // [see](https://github.com/protobufjs/protobuf.js#toolset)
    d. wm.WrappedMessageBytes = bytes
    e. wm.WrappedDescriptorId = descriptorId
    f. encodedWm = WrappedMessage.encode(wm).finish()
   g. bytebuf.write(encodedWm)
5. same for the value argument

_Get use case_
1. same steps as for Put when sending the request
2. A data buffer is received
3. wm = WrappedMessage.decode(buffer) // [see](https://github.com/protobufjs/protobuf.js#toolset)
4. pbTypeName = lookupProtostreamTypeById(wm.WrappedDescriptionId)
5. UserType = protobufRoot.lookupType(pbTypeName) // [see](https://github.com/protobufjs/protobuf.js#using-proto-files)
6. userObject = UserType.decode(wm.WrappedMessageBytes) // [see](https://github.com/protobufjs/protobuf.js#toolset)
7. return userObject

**Comment by NeerajGartia21** [comment]
It is an excellent and simplest design. It seems completely fine to me.

**Comment by rigazilla** [comment]
_Setup Time_ code has been implemented in #82

**Comment by rigazilla** [comment]
> * pbTypeName = lookupProtostreamTypeById(wm.WrappedDescriptionId)
> 
> * UserType = protobufRoot.lookupType(pbTypeName) // [see](https://github.com/protobufjs/protobuf.js#using-proto-files)

`protobufRoot` must contains all the protobuf definitions of the user data types. User must setup and pass it to the client. Client will provide an appropriate API call.
Code should look like:
*somewhere in user code*
```
// The user builds is own protobuf domain model
root = loadSync(filename)
loadSync(filename2, root)
loadSync(filename3, root)
// The user shares it with the client
client.registerUserProtobufRoot(root)
```
after the registration call the root object should be registered somewhere in the client and be available for encoding as described above

**Comment by rigazilla** [comment]
encoding added with #83

**Comment by rigazilla** [comment]
decoding impl is in #84
