### ISSUE TITLE
Implement PING v3.0 operation

### ISSUE THREAD

**Issue by rigazilla** [infinispan/js-client#74]
Client now support 2.9 hotrod protocol.

Task
Implement PING operation v3.0 so client can work with hotrod 3.0 protocol

**Comment by tristantarrant** [comment]
I assume 3.0 means >= 3.0

**Comment by rigazilla** [comment]
Version 3.0 extends PING operation response with additional information:
- the Hotrod server version 
- the list of the Hotrod operations supported by the server

Specification below comes from [Hotrod 3.0 ref](https://infinispan.org/docs/stable/titles/hotrod_protocol/hotrod_protocol.html#hot_rod_protocol_3_0)

**Version  2.9**
<div class="paragraph">
<p>Ping Response (0x18):</p>
</div>


Field Name | Size | Value
-- | -- | --
Header | variable | same as before
Response status | 1 byte | same as before
Key Type | MediaType | Media Type of the key stored in the server
Value Type | MediaType | Media Type of the value stored in the server

**Version  3.0**
<div class="paragraph"><p>Response (0x18):</p>
</div>


Field Name | Size | Value
-- | -- | --
Header | variable | Response header
Response status | 1 byte | 0x00 = success, if no errors
Key Type | MediaType | Media Type of the key stored in the server
Value Type | MediaType | Media Type of the value stored in the server
Version | 1 byte | Hot Rod server version.
opCount | vInt | Number of supported operations
opRequestCode1 | 1 byte | Request opcode of the first operation
…​ | …​ | …​
opRequestCodeN | 1 short | Request opcode of the nth operation

Development hints:
- An object for 3.0 (protocols.version30) should be added [here](https://github.com/infinispan/js-client/blob/f7065100ed32d3983d8e67ed5f06fafc95295dc6/lib/infinispan.js#L23)
- protocols.version30 should be able to read the additional info
- new info should be made available to the application developer (i.e. addedd somewhere as client ctx?)

**Comment by rigazilla** [comment]
Use the test suite to check the progress, i.e. setting 3.0 should make the testsuite fails at the beginning
then adding code should fix the test suite
