### ISSUE TITLE
Typescript adaptor

### ISSUE THREAD

**Issue by rigazilla** [infinispan/js-client#75]
A Typescript adaptation layer should be provide so to ease Infinispan-based Typescript applications dev

**Comment by BethGriggs** [comment]
Some potentially useful high-level information relating to TypeScript from the Red Hat Node.js team's reference architecture - https://nodeshift.dev/nodejs-reference-architecture/development/typescript

**Comment by rigazilla** [comment]
done with https://github.com/infinispan/js-client/pull/93
