### ISSUE TITLE
migrate off of request module

### ISSUE THREAD

**Issue by BethGriggs** [infinispan/js-client#80]
Request has been formally deprecated - https://www.npmjs.com/package/request

It's only used for tests in this module so is not urgent. But, it could be a potential `good first issue` to move off of it. 

I'd probably recommend `node-fetch` as an alternative. But `axios` and `got` are also good options (though have more dependencies, and `axios` has not yet reached v1.0.0).

**Comment by NeerajGartia21** [comment]
Since node-fetch from v3 is an ESM-only module. Is it fine to use node-fetch v2, so that it remains compatible with commonjs?

**Comment by BethGriggs** [comment]
I think v2 should be okay as it looks like they're patching both (just going by version publish history at https://snyk.io/vuln/npm:node-fetch as I couldn't find it documented). Otherwise either of the other two.
